name: "test / Test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - rel/**

  workflow_dispatch:

jobs:
  unit-test:
    name: "test / Test"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Rust and Wasm
        uses: ./.github/actions/setup-rust-wasm
        with:
          toolchain: nightly-2025-10-23
          install-cargo-deny: 'true'
          cache: 'true'

      - name: Setup Node and Display Info
        uses: ./.github/actions/setup-node-with-info
        with:
          node-version: 20

      - name: Fetch Base Ref
        run: |
          git fetch origin $GITHUB_BASE_REF

      - name: Install and Build Packages
        uses: ./.github/actions/npm-build

      - name: Check dependencies with cargo-deny
        run: cargo deny check
        working-directory: packages/wasm-utxo

      - name: test
        run: npx --version

      - name: Check Source Code Formatting
        run: npm run check-fmt

      - name: Wasm-Pack Test (Node)
        run: npm run test:wasm-pack-node
        working-directory: packages/wasm-utxo

      - name: Wasm-Pack Test (Chrome)
        run: npm run test:wasm-pack-chrome
        working-directory: packages/wasm-utxo

      - name: Unit Test
        run: npm --workspaces test
